services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: translations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - /db/init.sql:/docker-entrypoint-initdb.d/init.sql      
    networks:
      - db_network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/translations
    networks: [db_network, translator_network, frontend_network]
    depends_on:
      - db
      - translator

  frontend:
    build: ./frontend
    ports:
      - "8080:80" 
    depends_on:
      - backend 
    networks:
      - frontend_network  

  translator:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    depends_on:
      - db 
    networks:
      - translator_network     

volumes:
  db_data:

networks:
  frontend_network:
    driver: bridge
  db_network:
    driver: bridge
  translator_network:
    driver: bridge


    

